### ISSUE TITLE
filter-focus ignored if tests are run from a namespace called 'cljs

### ISSUE THREAD

**Issue by henryw374** [lambdaisland/kaocha-cljs2#30]
hello. I found a weird bug that took quite some time to track down... 

calling `(run)` function in this ns does not filter tests as expected. If I move the fn into a namespace with some other name, things work

```
(ns cljs)

(defn run []
  (kaocha.repl/run
            {:kaocha/tests
             [{:kaocha.testable/id   :browser-tests
               :kaocha.testable/type :kaocha.type/cljs2}]
             :kaocha.filter/focus [:skip-me  ]}))

```

**Comment by lambduhh** [comment]
Hi @henryw374 

Thank you for reporting! After reviewing the situation, it seems the root cause of the unexpected behavior when calling the `(run)` function from a namespace named `cljs` is due to a namespace naming conflict rather than a bug within the Kaocha library itself.

In ClojureScript, `cljs` is a reserved namespace prefix used extensively by the core libraries of the language. Naming a custom namespace as `cljs` can inadvertently lead to namespace shadowing. This means that the ClojureScript compiler and runtime might not be able to correctly resolve symbols or functions from the core `cljs` namespaces because it encounters your custom `cljs` namespace first. This shadowing can interfere with not only your code but also with any libraries (like Kaocha) that rely on the standard ClojureScript namespaces being available under their expected names.

You can find more about namespaces and their significance in the Clojure documentation here: [Clojure Namespaces](https://clojure.org/reference/namespaces) and a discussion about namespace best practices which, while not ClojureScript-specific, is highly relevant: [Library Development Guidelines](https://clojure.org/guides/libraries#_namespace_design). Although these resources are for Clojure, the principles apply to ClojureScript due to the shared design philosophy of both languages.

We recommend renaming your namespace from `cljs` to something more specific and not reserved by ClojureScript. This change should resolve the unexpected behavior and allow Kaocha to function as expected.

Thank you again for bringing this to our attention, and we appreciate your contribution to making Kaocha better. If you have any more questions or run into further issues, please feel free to reach out.

Happy hacking! ✌🏼

**Comment by henryw374** [comment]
ok thanks for letting me know.
